// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.linux:
        // TODO: Handle this case.
        throw UnimplementedError();
      case TargetPlatform.windows:
        // TODO: Handle this case.
        throw UnimplementedError();
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfR7Qo8Ag9wHcmxmMWAjh38pTFIzLWv20',
    appId: '1:601628093134:web:21ac3cf9e8349a64783e9f',
    messagingSenderId: '601628093134',
    projectId: 'pong-bot-6e353',
    authDomain: 'pong-bot-6e353.firebaseapp.com',
    storageBucket: 'pong-bot-6e353.appspot.com',
    measurementId: 'G-R2W1PWMKQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWYx9Qjzi7P7-SQgI9j9vOnEqrf0pr53g',
    appId: '1:601628093134:android:75257ddefeea6063783e9f',
    messagingSenderId: '601628093134',
    projectId: 'pong-bot-6e353',
    storageBucket: 'pong-bot-6e353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVbNhTJmfVtvgpiJVSCgHj7HRqykJsgY',
    appId: '1:601628093134:ios:49b9f3d28a1eab76783e9f',
    messagingSenderId: '601628093134',
    projectId: 'pong-bot-6e353',
    storageBucket: 'pong-bot-6e353.appspot.com',
    iosClientId: '601628093134-is3o4iveue6viv0kujlq55fpv5hlp54c.apps.googleusercontent.com',
    iosBundleId: 'pong.bot.app',
  );
}
